# WebSocket Support
proxy_set_header        Upgrade $http_upgrade;
proxy_set_header        Connection $connection_upgrade;

# Host and X headers
proxy_set_header        Host $host;
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Forwarded-Proto $scheme;

#proxy_set_header        Connection "";
add_header              X-Frame-Options "SAMEORIGIN";
add_header              X-XSS-Protection "1; mode=block" always;
add_header              Referrer-Policy "no-referrer-when-downgrade" always;
add_header              Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
add_header              Permissions-Policy "geolocation=(self), microphone=(self), camera=(self), fullscreen=(self)" always;
add_header              Content-Security-Policy "default-src * 'unsafe-inline' 'unsafe-eval' data: blob:;" always;
add_header              X-Content-Type-Options "nosniff" always;

# Connectivity Options
proxy_http_version      1.1;
proxy_buffering         off;
proxy_connect_timeout   3600s;
proxy_send_timeout      3600s;
proxy_read_timeout      3600s;
send_timeout            3600s;
proxy_socket_keepalive  on;

# Disable buffering
proxy_request_buffering off;
proxy_max_temp_file_size 0;