user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    map $ssl_preread_protocol $backend {
        "TLSv1.3"     web_backend;
        "TLSv1.2"     web_backend;
        "TLSv1.1"     web_backend;
        "TLSv1"       web_backend;
        default       ssh_backend;
    }

    upstream web_backend {
        server 127.0.0.1:4443;
    }

    upstream ssh_backend {
        server sish:2222;
    }

    server {
        listen 443;
        proxy_pass $backend;
        ssl_preread on;
        proxy_timeout 3600s;
        proxy_responses 1;
        proxy_protocol on;
    }
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;

    client_header_timeout         3600s;
    client_body_timeout           3600s;
    keepalive_timeout             300s;
    client_max_body_size          0;
    client_body_buffer_size       128k;
    client_header_buffer_size     3m;
    large_client_header_buffers 4 256k;

    include /etc/nginx/conf.d/*.conf;
}
