map $http_upgrade $connection_upgrade {
	default upgrade;
	'' close;
}

upstream sish {
    server sish:80;
    keepalive 32;
    keepalive_requests 100;
    keepalive_timeout 300s;
}

# Forced HTTP sites

#server {
#    server_name sish.mydomain.it;
#    client_max_body_size 0;
#    listen 80;
#    listen [::]:80;
#    client_header_timeout   3600s;
#    client_body_timeout     3600s;
#    location / {
#        include /nginx/common.conf;
#        proxy_pass http://sish;
#    }
#}

# Default proxy with redirect for *
server {
    server_name sish.mydomain.it *.sish.mydomain.it;
    client_max_body_size 0;
    listen 80 default_server;
    listen [::]:80;
    client_header_timeout   3600s;
    client_body_timeout     3600s;
    include /nginx/common.conf;
    return 301 https://$host$request_uri;
}

# Default proxy SSL
server {
     server_name sish.mydomain.it *.sish.mydomain.it;
     client_max_body_size 0;
     ssl_certificate     /certs/live/sish.mydomain.it/fullchain.pem;
     ssl_certificate_key /certs/live/sish.mydomain.it/privkey.pem;
     listen 4443 ssl proxy_protocol;
     set_real_ip_from 127.0.0.1;
     real_ip_header proxy_protocol;
     listen [::]:4443 ssl;
     ssl_protocols TLSv1.2 TLSv1.3;
     ssl_session_cache shared:SSL:10m;
     ssl_session_timeout 10m;
     client_header_timeout   3600s;
     client_body_timeout     3600s;
     location / {
         include /nginx/common.conf;
	 proxy_pass http://sish;
     }
}
