name: Test and Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
    branches:
      - main

env:
  PLATFORMS: |
    linux/arm/v7
    linux/arm64
    linux/amd64
  TAGS: |
    type=schedule
    type=ref,event=branch
    type=ref,event=tag
    type=ref,event=pr
    type=sha,prefix=,suffix=,format=long

jobs:
  validate-tag:
    runs-on: ubuntu-24.04
    outputs:
      valid: ${{ steps.check.outputs.valid }}
    steps:
    - name: Validate tag format
      id: check
      run: |
        if [[ "${GITHUB_REF}" != refs/tags/* ]]; then
          echo "valid=true" >> "$GITHUB_OUTPUT"
        elif echo "${GITHUB_REF_NAME}" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
          echo "valid=true" >> "$GITHUB_OUTPUT"
        else
          echo "valid=false" >> "$GITHUB_OUTPUT"
        fi

  test:
    if: ${{ false }}
    needs: [validate-tag]
    runs-on: ubuntu-24.04
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26.1
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Lint the codebase
      uses: golangci/golangci-lint-action@v9
      with:
        version: latest
    - name: Run tests
      if: ${{ false }}
      run: |
        echo "Tests are disabled"
  build:
    runs-on: ubuntu-24.04
    needs: [validate-tag]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Collect image metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
        tags: ${{ env.TAGS }}
    - name: Collect build image metadata
      id: buildmeta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}-build-image
        tags: ${{ env.TAGS }}
    - name: Build and push release
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.actor == github.repository_owner }}
        load: ${{ github.actor != github.repository_owner }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        target: release
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}-cache
        cache-to: |
          ${{ github.actor == github.repository_owner && format('type=registry,ref=ghcr.io/{0}-cache,mode=max', github.repository) || '' }}
        platforms: ${{ github.actor == github.repository_owner && env.PLATFORMS || 'linux/amd64' }}
        build-args: |
          DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          COMMIT=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
          REPOSITORY=${{ github.repository }}
    - name: Build and push build image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: ${{ github.actor == github.repository_owner }}
        load: ${{ github.actor != github.repository_owner }}
        tags: ${{ steps.buildmeta.outputs.tags }}
        labels: ${{ steps.buildmeta.outputs.labels }}
        target: build-image
        cache-from: |
          type=registry,ref=ghcr.io/${{ github.repository }}-cache
        cache-to: |
          ${{ github.actor == github.repository_owner && format('type=registry,ref=ghcr.io/{0}-cache,mode=max', github.repository) || '' }}
        platforms: ${{ github.actor == github.repository_owner && env.PLATFORMS || 'linux/amd64' }}
        build-args: |
          DATE=${{ fromJSON(steps.buildmeta.outputs.json).labels['org.opencontainers.image.created'] }}
          VERSION=${{ fromJSON(steps.buildmeta.outputs.json).labels['org.opencontainers.image.version'] }}
          COMMIT=${{ fromJSON(steps.buildmeta.outputs.json).labels['org.opencontainers.image.revision'] }}
          REPOSITORY=${{ github.repository }}
